name: Print Head

on:
  pull_request:

jobs:
  print:
    runs-on: ubuntu-latest
    name: print head
    env:
      head: ${{ github.head_ref }}
    steps:
    - run: echo ${{ toJSON(github.event.pull_request.title) }}
